Repository swcarpentry/sql-novice-survey, pull requests merged in 2018-04, with the labels that each got.

#225 Add solution to 'Averaging with NULL'
  _episodes/06-agg.md
Labels: enhancement

#224 Add solution to 'Selecting Major Site Identifiers'
  _episodes/04-calc.md
Labels: enhancement

#227 Add solution for 'Backing up with SQL'
  _episodes/09-create.md
Labels: enhancement

#226 Add solutions for episode 08
  _episodes/08-hygiene.md
Labels: enhancement

#165 Update style
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
  CONDUCT.md
  LICENSE.md
  Makefile
  _includes/carpentries.html
  _includes/dc/intro.html
  _includes/dc/schedule.html
  _includes/dc/syllabus.html
  _includes/dc/who.html
  _includes/episode_keypoints.html
  _includes/episode_navbar.html
  _includes/episode_title.html
  _includes/javascript.html
  _includes/lc/intro.html
  _includes/lc/schedule.html
  _includes/lc/syllabus.html
  _includes/lc/who.html
  _includes/lesson_footer.html
  _includes/links.md
  _includes/main_title.html
  _includes/navbar.html
  _includes/sc/intro.html
  _includes/sc/schedule.html
  _includes/sc/syllabus.html
  _includes/sc/who.html
  _includes/syllabus.html
  _includes/workshop_ad.html
  _includes/workshop_footer.html
  _layouts/base.html
  _layouts/break.html
  _layouts/episode.html
  _layouts/workshop.html
  assets/css/bootstrap.css
  assets/css/lesson.scss
  assets/css/syntax.css
  assets/img/lc-icon-black.png
  assets/img/lc-icon-black.svg
  assets/img/swc-icon-blue.svg
  assets/img/swc-logo-blue.svg
  assets/img/swc-logo-white.svg
  assets/js/jquery.min.map
  assets/js/lesson.js
  bin/chunk-options.R
  bin/extract_figures.py
  bin/generate_md_episodes.R
  bin/lesson_check.py
  bin/lesson_initialize.py
  bin/repo_check.py
  bin/util.py
  bin/workshop_check.py
  favicon-lc.ico
Labels: help-wanted, template-and-tools

#234 Fix missing markup for a solution
  _episodes/04-calc.md
Labels: bug
